name: Continue on Error and timeout

on: [push]

jobs:
    run-shell-command1:
      runs-on: ubuntu-latest
      steps:
      
        - name: echooooooooo a string
          run: echoooooooooooo "hello"
          continue-on-error: true
        - name: echo a string
          run: |
            node -v
            npm -v            
        - name: python  Command
      
          run: |
            import platform
            print(platform.processor())
          shell: python
             
    run-shell-command2:
      runs-on: ubuntu-latest
      needs: [run-shell-command1]
      steps:
        - name: echo a string
          run: echo "hello1"
        - name: echo a string
          run: |
            node -v
            npm -v                
        - name: python  Command
          run: |
            import platform
            print(platform.processor())
          shell: python       
