name: 2 Jobs one after the other 

on: [push]

jobs:
    run-shell-command1:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "hello"
        - name: echo a string
          run: |
            node -v
            npm -v            
        - name: python  Command
          run: |
            import platform
            print(platform.processor())
          shell: python
             
    run-shell-command2:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "hello1"
        - name: echo a string
          run: |
            node -v
            npm -v                
        - name: python  Command
          run: |
            import platform
            print(platform.processor())
          shell: python       
