name: shell Commands

on: [push]

jobs:
    run-shell-command:
      run-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "hello"
        - name: echo a string
          run: |
            node -v
            npm -v 
